const ID_DETAIL_MOVIE = "ID_DETAIL_MOVIE";
const ADMIN_SELECT_STATE = "ADMIN_SELECT_STATE";
const USER_LOGIN = "USER_LOGIN";
const ID_MOVIE_BUY_TICKET = "ID_MOVIE_BUY_TICKET";

export { ID_DETAIL_MOVIE, ADMIN_SELECT_STATE, USER_LOGIN, ID_MOVIE_BUY_TICKET };
